# Generated by Django 3.0.5 on 2020-04-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_tools_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='availability',
        ),
    ]
