# Generated by Django 3.0.5 on 2020-04-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_tool_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='availability',
            new_name='vailability',
        ),
    ]
