# Generated by Django 3.0.5 on 2020-04-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200421_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
