# Generated by Django 3.0.5 on 2020-04-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='availability',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
