# Generated by Django 3.0.5 on 2020-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200421_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='availability',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
